/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const AnnouncementCategory = IDL.Variant({
  'event' : IDL.Null,
  'urgent' : IDL.Null,
  'general' : IDL.Null,
});
export const Announcement = IDL.Record({
  'title' : IDL.Text,
  'body' : IDL.Text,
  'date' : Time,
  'pinned' : IDL.Bool,
  'category' : AnnouncementCategory,
});
export const PaymentMethod = IDL.Variant({
  'MTN' : IDL.Null,
  'Bank' : IDL.Null,
  'Airtel' : IDL.Null,
});
export const Currency = IDL.Variant({
  'KES' : IDL.Null,
  'RWF' : IDL.Null,
  'UGX' : IDL.Null,
  'USD' : IDL.Null,
});
export const ContributionCategory = IDL.Variant({
  'Musabaka' : IDL.Null,
  'Irayidi' : IDL.Null,
  'ZakatulFitr' : IDL.Null,
});
export const Contribution = IDL.Record({
  'member' : IDL.Opt(IDL.Principal),
  'paymentMethod' : PaymentMethod,
  'note' : IDL.Opt(IDL.Text),
  'donorName' : IDL.Text,
  'currency' : Currency,
  'timestamp' : Time,
  'category' : ContributionCategory,
  'amount' : IDL.Float64,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Meeting = IDL.Record({
  'title' : IDL.Text,
  'date' : Time,
  'minutes' : IDL.Opt(IDL.Text),
  'agenda' : IDL.Text,
  'location' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const MeetingComment = IDL.Record({
  'comment' : IDL.Text,
  'memberName' : IDL.Text,
  'timestamp' : Time,
  'meetingId' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAnnouncement' : IDL.Func([Announcement], [IDL.Nat], []),
  'addContribution' : IDL.Func([Contribution], [IDL.Nat], []),
  'addMeetingComment' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createMeeting' : IDL.Func([Meeting], [IDL.Nat], []),
  'deleteAnnouncement' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteContribution' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getAllAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
  'getAllMeetings' : IDL.Func([], [IDL.Vec(Meeting)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContributionTotalsByCategory' : IDL.Func(
      [ContributionCategory],
      [IDL.Float64],
      ['query'],
    ),
  'getContributionsByCategory' : IDL.Func(
      [ContributionCategory],
      [IDL.Vec(Contribution)],
      ['query'],
    ),
  'getMeetingComments' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(MeetingComment)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'pinAnnouncement' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const AnnouncementCategory = IDL.Variant({
    'event' : IDL.Null,
    'urgent' : IDL.Null,
    'general' : IDL.Null,
  });
  const Announcement = IDL.Record({
    'title' : IDL.Text,
    'body' : IDL.Text,
    'date' : Time,
    'pinned' : IDL.Bool,
    'category' : AnnouncementCategory,
  });
  const PaymentMethod = IDL.Variant({
    'MTN' : IDL.Null,
    'Bank' : IDL.Null,
    'Airtel' : IDL.Null,
  });
  const Currency = IDL.Variant({
    'KES' : IDL.Null,
    'RWF' : IDL.Null,
    'UGX' : IDL.Null,
    'USD' : IDL.Null,
  });
  const ContributionCategory = IDL.Variant({
    'Musabaka' : IDL.Null,
    'Irayidi' : IDL.Null,
    'ZakatulFitr' : IDL.Null,
  });
  const Contribution = IDL.Record({
    'member' : IDL.Opt(IDL.Principal),
    'paymentMethod' : PaymentMethod,
    'note' : IDL.Opt(IDL.Text),
    'donorName' : IDL.Text,
    'currency' : Currency,
    'timestamp' : Time,
    'category' : ContributionCategory,
    'amount' : IDL.Float64,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Meeting = IDL.Record({
    'title' : IDL.Text,
    'date' : Time,
    'minutes' : IDL.Opt(IDL.Text),
    'agenda' : IDL.Text,
    'location' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const MeetingComment = IDL.Record({
    'comment' : IDL.Text,
    'memberName' : IDL.Text,
    'timestamp' : Time,
    'meetingId' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAnnouncement' : IDL.Func([Announcement], [IDL.Nat], []),
    'addContribution' : IDL.Func([Contribution], [IDL.Nat], []),
    'addMeetingComment' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createMeeting' : IDL.Func([Meeting], [IDL.Nat], []),
    'deleteAnnouncement' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteContribution' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getAllAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
    'getAllMeetings' : IDL.Func([], [IDL.Vec(Meeting)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContributionTotalsByCategory' : IDL.Func(
        [ContributionCategory],
        [IDL.Float64],
        ['query'],
      ),
    'getContributionsByCategory' : IDL.Func(
        [ContributionCategory],
        [IDL.Vec(Contribution)],
        ['query'],
      ),
    'getMeetingComments' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(MeetingComment)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'pinAnnouncement' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };