/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Announcement {
  'title' : string,
  'body' : string,
  'date' : Time,
  'pinned' : boolean,
  'category' : AnnouncementCategory,
}
export type AnnouncementCategory = { 'event' : null } |
  { 'urgent' : null } |
  { 'general' : null };
export interface Contribution {
  'member' : [] | [Principal],
  'paymentMethod' : PaymentMethod,
  'note' : [] | [string],
  'donorName' : string,
  'currency' : Currency,
  'timestamp' : Time,
  'category' : ContributionCategory,
  'amount' : number,
}
export type ContributionCategory = { 'Musabaka' : null } |
  { 'Irayidi' : null } |
  { 'ZakatulFitr' : null };
export type Currency = { 'KES' : null } |
  { 'RWF' : null } |
  { 'UGX' : null } |
  { 'USD' : null };
export interface Meeting {
  'title' : string,
  'date' : Time,
  'minutes' : [] | [string],
  'agenda' : string,
  'location' : string,
}
export interface MeetingComment {
  'comment' : string,
  'memberName' : string,
  'timestamp' : Time,
  'meetingId' : bigint,
}
export type PaymentMethod = { 'MTN' : null } |
  { 'Bank' : null } |
  { 'Airtel' : null };
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAnnouncement' : ActorMethod<[Announcement], bigint>,
  'addContribution' : ActorMethod<[Contribution], bigint>,
  'addMeetingComment' : ActorMethod<[bigint, string, string], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createMeeting' : ActorMethod<[Meeting], bigint>,
  'deleteAnnouncement' : ActorMethod<[bigint], boolean>,
  'deleteContribution' : ActorMethod<[bigint], boolean>,
  'getAllAnnouncements' : ActorMethod<[], Array<Announcement>>,
  'getAllMeetings' : ActorMethod<[], Array<Meeting>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContributionTotalsByCategory' : ActorMethod<
    [ContributionCategory],
    number
  >,
  'getContributionsByCategory' : ActorMethod<
    [ContributionCategory],
    Array<Contribution>
  >,
  'getMeetingComments' : ActorMethod<[bigint], Array<MeetingComment>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'pinAnnouncement' : ActorMethod<[bigint], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];