/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface Meeting {
    title: string;
    date: Time;
    minutes?: string;
    agenda: string;
    location: string;
}
export interface Contribution {
    member?: Principal;
    paymentMethod: PaymentMethod;
    note?: string;
    donorName: string;
    currency: Currency;
    timestamp: Time;
    category: ContributionCategory;
    amount: number;
}
export interface Announcement {
    title: string;
    body: string;
    date: Time;
    pinned: boolean;
    category: AnnouncementCategory;
}
export interface MeetingComment {
    comment: string;
    memberName: string;
    timestamp: Time;
    meetingId: bigint;
}
export interface UserProfile {
    name: string;
}
export enum AnnouncementCategory {
    event = "event",
    urgent = "urgent",
    general = "general"
}
export enum ContributionCategory {
    Musabaka = "Musabaka",
    Irayidi = "Irayidi",
    ZakatulFitr = "ZakatulFitr"
}
export enum Currency {
    KES = "KES",
    RWF = "RWF",
    UGX = "UGX",
    USD = "USD"
}
export enum PaymentMethod {
    MTN = "MTN",
    Bank = "Bank",
    Airtel = "Airtel"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addAnnouncement(announcement: Announcement): Promise<bigint>;
    addContribution(contribution: Contribution): Promise<bigint>;
    addMeetingComment(meetingId: bigint, memberName: string, comment: string): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createMeeting(meeting: Meeting): Promise<bigint>;
    deleteAnnouncement(announcementId: bigint): Promise<boolean>;
    deleteContribution(contributionId: bigint): Promise<boolean>;
    getAllAnnouncements(): Promise<Array<Announcement>>;
    getAllMeetings(): Promise<Array<Meeting>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getContributionTotalsByCategory(category: ContributionCategory): Promise<number>;
    getContributionsByCategory(category: ContributionCategory): Promise<Array<Contribution>>;
    getMeetingComments(meetingId: bigint): Promise<Array<MeetingComment>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    pinAnnouncement(announcementId: bigint): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
}
import type { Announcement as _Announcement, AnnouncementCategory as _AnnouncementCategory, Contribution as _Contribution, ContributionCategory as _ContributionCategory, Currency as _Currency, Meeting as _Meeting, PaymentMethod as _PaymentMethod, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addAnnouncement(arg0: Announcement): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addAnnouncement(to_candid_Announcement_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAnnouncement(to_candid_Announcement_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addContribution(arg0: Contribution): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addContribution(to_candid_Contribution_n5(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addContribution(to_candid_Contribution_n5(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addMeetingComment(arg0: bigint, arg1: string, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addMeetingComment(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMeetingComment(arg0, arg1, arg2);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n13(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n13(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createMeeting(arg0: Meeting): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createMeeting(to_candid_Meeting_n15(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMeeting(to_candid_Meeting_n15(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteAnnouncement(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAnnouncement(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAnnouncement(arg0);
            return result;
        }
    }
    async deleteContribution(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteContribution(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteContribution(arg0);
            return result;
        }
    }
    async getAllAnnouncements(): Promise<Array<Announcement>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAnnouncements();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAnnouncements();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllMeetings(): Promise<Array<Meeting>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMeetings();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMeetings();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getContributionTotalsByCategory(arg0: ContributionCategory): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getContributionTotalsByCategory(to_candid_ContributionCategory_n11(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContributionTotalsByCategory(to_candid_ContributionCategory_n11(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getContributionsByCategory(arg0: ContributionCategory): Promise<Array<Contribution>> {
        if (this.processError) {
            try {
                const result = await this.actor.getContributionsByCategory(to_candid_ContributionCategory_n11(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContributionsByCategory(to_candid_ContributionCategory_n11(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMeetingComments(arg0: bigint): Promise<Array<MeetingComment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMeetingComments(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMeetingComments(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async pinAnnouncement(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.pinAnnouncement(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.pinAnnouncement(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
}
function from_candid_AnnouncementCategory_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AnnouncementCategory): AnnouncementCategory {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_Announcement_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Announcement): Announcement {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_ContributionCategory_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ContributionCategory): ContributionCategory {
    return from_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function from_candid_Contribution_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Contribution): Contribution {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_Currency_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Currency): Currency {
    return from_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function from_candid_Meeting_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Meeting): Meeting {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentMethod_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentMethod): PaymentMethod {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    body: string;
    date: _Time;
    pinned: boolean;
    category: _AnnouncementCategory;
}): {
    title: string;
    body: string;
    date: Time;
    pinned: boolean;
    category: AnnouncementCategory;
} {
    return {
        title: value.title,
        body: value.body,
        date: value.date,
        pinned: value.pinned,
        category: from_candid_AnnouncementCategory_n20(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    date: _Time;
    minutes: [] | [string];
    agenda: string;
    location: string;
}): {
    title: string;
    date: Time;
    minutes?: string;
    agenda: string;
    location: string;
} {
    return {
        title: value.title,
        date: value.date,
        minutes: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.minutes)),
        agenda: value.agenda,
        location: value.location
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    member: [] | [Principal];
    paymentMethod: _PaymentMethod;
    note: [] | [string];
    donorName: string;
    currency: _Currency;
    timestamp: _Time;
    category: _ContributionCategory;
    amount: number;
}): {
    member?: Principal;
    paymentMethod: PaymentMethod;
    note?: string;
    donorName: string;
    currency: Currency;
    timestamp: Time;
    category: ContributionCategory;
    amount: number;
} {
    return {
        member: record_opt_to_undefined(from_candid_opt_n32(_uploadFile, _downloadFile, value.member)),
        paymentMethod: from_candid_PaymentMethod_n33(_uploadFile, _downloadFile, value.paymentMethod),
        note: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.note)),
        donorName: value.donorName,
        currency: from_candid_Currency_n35(_uploadFile, _downloadFile, value.currency),
        timestamp: value.timestamp,
        category: from_candid_ContributionCategory_n37(_uploadFile, _downloadFile, value.category),
        amount: value.amount
    };
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    event: null;
} | {
    urgent: null;
} | {
    general: null;
}): AnnouncementCategory {
    return "event" in value ? AnnouncementCategory.event : "urgent" in value ? AnnouncementCategory.urgent : "general" in value ? AnnouncementCategory.general : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    MTN: null;
} | {
    Bank: null;
} | {
    Airtel: null;
}): PaymentMethod {
    return "MTN" in value ? PaymentMethod.MTN : "Bank" in value ? PaymentMethod.Bank : "Airtel" in value ? PaymentMethod.Airtel : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    KES: null;
} | {
    RWF: null;
} | {
    UGX: null;
} | {
    USD: null;
}): Currency {
    return "KES" in value ? Currency.KES : "RWF" in value ? Currency.RWF : "UGX" in value ? Currency.UGX : "USD" in value ? Currency.USD : value;
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Musabaka: null;
} | {
    Irayidi: null;
} | {
    ZakatulFitr: null;
}): ContributionCategory {
    return "Musabaka" in value ? ContributionCategory.Musabaka : "Irayidi" in value ? ContributionCategory.Irayidi : "ZakatulFitr" in value ? ContributionCategory.ZakatulFitr : value;
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Announcement>): Array<Announcement> {
    return value.map((x)=>from_candid_Announcement_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Meeting>): Array<Meeting> {
    return value.map((x)=>from_candid_Meeting_n23(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Contribution>): Array<Contribution> {
    return value.map((x)=>from_candid_Contribution_n30(_uploadFile, _downloadFile, x));
}
function to_candid_AnnouncementCategory_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AnnouncementCategory): _AnnouncementCategory {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_Announcement_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Announcement): _Announcement {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_ContributionCategory_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ContributionCategory): _ContributionCategory {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_Contribution_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Contribution): _Contribution {
    return to_candid_record_n6(_uploadFile, _downloadFile, value);
}
function to_candid_Currency_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Currency): _Currency {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_Meeting_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Meeting): _Meeting {
    return to_candid_record_n16(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentMethod_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): _PaymentMethod {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    date: Time;
    minutes?: string;
    agenda: string;
    location: string;
}): {
    title: string;
    date: _Time;
    minutes: [] | [string];
    agenda: string;
    location: string;
} {
    return {
        title: value.title,
        date: value.date,
        minutes: value.minutes ? candid_some(value.minutes) : candid_none(),
        agenda: value.agenda,
        location: value.location
    };
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    body: string;
    date: Time;
    pinned: boolean;
    category: AnnouncementCategory;
}): {
    title: string;
    body: string;
    date: _Time;
    pinned: boolean;
    category: _AnnouncementCategory;
} {
    return {
        title: value.title,
        body: value.body,
        date: value.date,
        pinned: value.pinned,
        category: to_candid_AnnouncementCategory_n3(_uploadFile, _downloadFile, value.category)
    };
}
function to_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    member?: Principal;
    paymentMethod: PaymentMethod;
    note?: string;
    donorName: string;
    currency: Currency;
    timestamp: Time;
    category: ContributionCategory;
    amount: number;
}): {
    member: [] | [Principal];
    paymentMethod: _PaymentMethod;
    note: [] | [string];
    donorName: string;
    currency: _Currency;
    timestamp: _Time;
    category: _ContributionCategory;
    amount: number;
} {
    return {
        member: value.member ? candid_some(value.member) : candid_none(),
        paymentMethod: to_candid_PaymentMethod_n7(_uploadFile, _downloadFile, value.paymentMethod),
        note: value.note ? candid_some(value.note) : candid_none(),
        donorName: value.donorName,
        currency: to_candid_Currency_n9(_uploadFile, _downloadFile, value.currency),
        timestamp: value.timestamp,
        category: to_candid_ContributionCategory_n11(_uploadFile, _downloadFile, value.category),
        amount: value.amount
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Currency): {
    KES: null;
} | {
    RWF: null;
} | {
    UGX: null;
} | {
    USD: null;
} {
    return value == Currency.KES ? {
        KES: null
    } : value == Currency.RWF ? {
        RWF: null
    } : value == Currency.UGX ? {
        UGX: null
    } : value == Currency.USD ? {
        USD: null
    } : value;
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ContributionCategory): {
    Musabaka: null;
} | {
    Irayidi: null;
} | {
    ZakatulFitr: null;
} {
    return value == ContributionCategory.Musabaka ? {
        Musabaka: null
    } : value == ContributionCategory.Irayidi ? {
        Irayidi: null
    } : value == ContributionCategory.ZakatulFitr ? {
        ZakatulFitr: null
    } : value;
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AnnouncementCategory): {
    event: null;
} | {
    urgent: null;
} | {
    general: null;
} {
    return value == AnnouncementCategory.event ? {
        event: null
    } : value == AnnouncementCategory.urgent ? {
        urgent: null
    } : value == AnnouncementCategory.general ? {
        general: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): {
    MTN: null;
} | {
    Bank: null;
} | {
    Airtel: null;
} {
    return value == PaymentMethod.MTN ? {
        MTN: null
    } : value == PaymentMethod.Bank ? {
        Bank: null
    } : value == PaymentMethod.Airtel ? {
        Airtel: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
